package sh.ondr.kmcp.ksp

import com.google.devtools.ksp.processing.Dependencies

fun KmcpProcessor.generateInitializer() {
	val name = if (isTest) "KmcpTestInitializer" else "KmcpInitializer"
	val kmcpInitializerPackage = "$pkg.generated.initializer"
	val file = codeGenerator.createNewFile(
		dependencies = Dependencies(
			aggregating = true,
			sources = tools.map { it.originatingFile }.toTypedArray(),
		),
		packageName = kmcpInitializerPackage,
		fileName = name,
	)

	val code = buildString {
		appendLine("// Generated by kmcp")
		appendLine("package $kmcpInitializerPackage")
		appendLine()
		appendLine("import sh.ondr.kmcp.runtime.core.mcpPromptParams")
		appendLine("import sh.ondr.kmcp.runtime.core.mcpPromptHandlers")
		appendLine("import sh.ondr.kmcp.runtime.core.mcpToolParams")
		appendLine("import sh.ondr.kmcp.runtime.core.mcpToolHandlers")
		if (tools.isNotEmpty()) {
			appendLine("import $kmcpHandlersPackage.*")
			appendLine("import $kmcpParamsPackage.*")
		}
		appendLine("import kotlin.reflect.KClass")
		appendLine()
		appendLine("object $name {")
		appendLine("  init {")

		for (tool in tools) {
			val handlerClassName = tool.functionName.replaceFirstChar { it.uppercase() } + "McpToolHandler"
			val paramsClassName = tool.paramsClassName
			appendLine("    // Register '${tool.functionName}'")
			appendLine("    mcpToolParams[\"${tool.functionName}\"] = $paramsClassName::class")
			appendLine("    mcpToolHandlers[\"${tool.functionName}\"] = $handlerClassName()")
		}

		for (prompt in prompts) {
			val handlerClassName = prompt.functionName.replaceFirstChar { it.uppercase() } + "McpPromptHandler"
			val paramsClassName = prompt.paramsClassName
			appendLine("    // Register '${prompt.functionName}'")
			appendLine("    mcpPromptParams[\"${prompt.functionName}\"] = $paramsClassName::class")
			appendLine("    mcpPromptHandlers[\"${prompt.functionName}\"] = $handlerClassName()")
		}

		appendLine("  }")
		appendLine("}")
	}

	file.write(code.toByteArray())
	file.close()
}
